[package]
name = "user-service"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
sqlx = { workspace = true }
jsonwebtoken = { workspace = true }
dotenvy = { workspace = true }
